ASEH_Front/Controllers/ChController.cs
﻿using ASEH_Front.Models;
using ASEH_Front.Models.Article;
using ASEH_Front.Models.Common.Quest;
using ASEH_Front.Models.Download;
using ASEH_Front.Models.ReportQuestionnaire;
using Models;
using Newtonsoft.Json;
using Service.BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using web.ViewModels.GoogleSearch;
using ASEH_Backend.Services;

namespace ASEH_Front.Controllers
{
    [OutputCache(NoStore = true, Duration = 0)]
    public class ChController : BaseController
    {
        UserService userService = new UserService();
        public ChController()
        {
            this.lang = "ch";
        }

        public ActionResult News_Login()
        {
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();
            try
            {
                validToken();
                return RedirectToAction("News_Profile");
            }
            catch (Exception)
            {

            }

            return View(new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }

        [HttpPost]
        public ActionResult News_Login(NewsUser data)
        {
            this.Init();
            var serv = new UserService();
            ViewBag.CountryList = Db.Country.ToList();
            try
            {
                var user = serv.Login(data.Account, data.Password);
                var token = serv.GetToken(user, 180);
                Session["NewsUserToken"] = token;
                TempData["Message"] = "登入成功";
                return RedirectToAction("News_Profile");
            }
            catch (Exception err)
            {
                ViewBag.Message = "登入失敗";
                ViewBag.IsError = true;
            }

            return View(new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }

        public ActionResult News_Register()
        {
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();

            return View("News_Login", new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }

        [HttpPost]
        public ActionResult News_Register(NewsUser data)
        {
            
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();

            var ConfirmPassword = HttpContext.Request.Form.Get("ConfirmPassword");
            var serv = new UserService();
            try
            {
                if ( Request.Cookies["CAPTCHA"].Value != this.Request.Form.Get("VerifyCode") )
                {
                    throw new Exception("驗證碼錯誤");
                }
                if ( ConfirmPassword != data.Password )
                {
                    throw new Exception("密碼與確認密碼不一致");
                }
                data.Email = data.Account;

                try
                {
                    serv.Add(data);
                }
                catch (Exception)
                {
                    throw new Exception("電子信箱重覆");
                }
                TempData["Message"] = "註冊成功";
                return RedirectToAction("News_Login");
            } catch ( Exception err )
            {
                ViewBag.IsError = true;
                ViewBag.Message = err.Message;
            }
            
            return View("News_Login", data);
        }

        public ActionResult News_Logout()
        {
            this.Init();
            this.Logout();

            return RedirectToAction("News_Login");
        }

        public ActionResult News_Edit_Profile()
        {
            this.Init();
            try
            {
                var sessionData = validToken();
                var dbData = userService.GetById(sessionData.Id);

                ViewBag.CountryList = Db.Country.ToList();
                return View(dbData);
            } catch ( Exception )
            {
                return RedirectToAction("News_Login");
            }
            
        }

   

        [HttpPost]
        public ActionResult News_Edit_Profile(NewsUser data )
        {
            this.Init();

            
            try
            {
                var sessionUser = validToken();
                try
                {
                    var serv = new UserService();
                    serv.Update(sessionUser.Id, data);
                    TempData["Message"] = "變更資料成功";
                    return RedirectToAction("News_Profile");
                } catch ( Exception err )
                {
                    ViewBag.CountryList = Db.Country.ToList();
                    ViewBag.Message = "電子信箱重覆";
                    ViewBag.IsError = true;
                    return View(sessionUser);
                }
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }
            
        }

        public ActionResult News_Edit_Password()
        {
            this.Init();
            return View();
        }

        [HttpPost]
        public ActionResult News_Edit_Password(FormCollection form)
        {
            string Password = form.Get("Password");
            string ConfirmPassword = form.Get("ConfirmPassword");
            try
            {
                var serv = new UserService();
                var sessionUser = validToken();
                
                if (Password != ConfirmPassword)
                {
                    ViewBag.Message = "新密碼與確認密碼不一致";
                    ViewBag.IsError = true;
                }
                else
                {
                    userService.ResetPassword(sessionUser.Id, Password);
                    TempData["Message"] = "變更密碼成功";
                    return RedirectToAction("News_Profile");
                }
                this.Init();
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }
            
        }

        public ActionResult News_Forget(string token)
        {
            this.Init();
            if (token != null)
            {
                try
                {
                    var dbData = userService.ValidToken(token);
                    ViewBag.Token = token;
                }
                catch (Exception err)
                {
                    ViewBag.Message = "變更密碼時效已過";
                    ViewBag.IsError = true;
                }
            }
            
            return View();
        }

        [HttpPost]
        public ActionResult News_Forget(FormCollection form)
        {
            var Token = form.Get("Token");
            if ( Token == null )
            {
                // CheckEmail
                var Email = form.Get("Email");
                try
                {
                    var dbData = userService.GetByEmail(Email);

                    //return RedirectToAction("News_Forget", new
                    //{
                    //    token = userService.GetToken(dbData, 30)
                    //});
                    userService.SendForgetEmail(dbData.Id);
                    TempData["Message"] = "Email 驗證成功，請收取驗證信。";
                    return RedirectToAction("News_Login");
                }
                catch (Exception err)
                {
                    ViewBag.Message = "此Email尚未註冊";
                    ViewBag.IsError = true;
                }

            } else
            {
                //Update Password
                var Password = form.Get("Password");
                var ConfirmPassword = form.Get("ConfirmPassword");
                if ( Password != ConfirmPassword )
                {
                    ViewBag.Message = "新密碼與確認密碼不一致";
                    ViewBag.IsError = true;
                } else
                {
                    try
                    {
                        var tokenData = userService.ValidToken(Token);
                        userService.ResetPassword(tokenData.Id, Password);
                        TempData["Message"] = "變更密碼成功，請使用新的密碼進行登入";
                        return RedirectToAction("News_Login");
                    }
                    catch (Exception)
                    {
                        ViewBag.Message = "變更密碼時效已過";
                        ViewBag.IsError = true;
                        return RedirectToAction("News_Forget");
                    }
                }
                
            }
            
            this.Init();
            return View();
        }


       

        public ActionResult News_Profile()
        {
            this.Init();
            try
            {
                validToken();
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }

            return View();
        }

        public ActionResult Milestones()
        {
            this.Init();
            return this.View();
        }
        

        public ActionResult Search(string q = "", int page = 1)
        {
            this.Init();

            string searchUrl = String.Format("https://www.googleapis.com/customsearch/v1?key=AIzaSyCoIG9dTAyeNTxVWaAPZ2leVdt8f3MZm0c&cx=017526043270526596107:s1vtx3mblil&q={0}&start={1}", q, ((page - 1) * 10) + 1);
            WebRequest req = HttpWebRequest.Create(searchUrl);

            req.ContentType = "application/json";


            GoogleSearchResult result;
            string body;
            // 取得回應資料
            using (HttpWebResponse response = req.GetResponse() as HttpWebResponse)
            {
                using (StreamReader sr = new StreamReader(response.GetResponseStream()))
                {
                    body = sr.ReadToEnd();
                    result = GoogleSearchResult.FromJson(body);
                }

ASEH_Front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ASEH_Front/Views/Shared/_Layout_Base.cshtml
@using ASEH_Front.Models
@using System.Text.RegularExpressions;
@{
    List<SiteNav> site_nav_list = ViewBag.site_nav_list;
    string currentUrl = Request.Url.PathAndQuery;
    string enUrl = new Regex("/ch").Replace(currentUrl, "/en", 1);
    string chUrl = currentUrl;
}

@helper renderMenu(List<SiteNav>
  navList, string classPrefix, int lv = 1, string checkboxIdPrefix = "")
{
    foreach (var nav in navList)
    {
        string checkboxId = @String.Format("{0}__Lv{1}__Checkbox__{2}-{3}", classPrefix, lv, checkboxIdPrefix, nav.No);
        bool hasUrl = nav.Url != "";
        bool hasChildren = nav.Children.Count() > 0;
        <div class="@String.Format("{0}__Lv{1}Item", classPrefix, lv)">
            <input type="checkbox" id="@checkboxId" />
            <div class="@String.Format("NavHeader", classPrefix, lv)">
                @if (hasUrl)
                {
                    <a class="NavTitle" href="@nav.Url" data-title="@nav.Title" data-href="@nav.Url">@nav.Title</a>
                }
                else
                {
                    <div class="NavTitle" href="@nav.Url" data-title="@nav.Title" data-href="@nav.Url">@nav.Title</div>
                }
                @if (hasChildren)
                {
                    <label for="@checkboxId" class="@String.Format("NavHeader__Toggle", classPrefix, lv)">
                        <i class="glyphicon glyphicon-triangle-bottom"></i>
                    </label>
                }
            </div>


            @if (nav.Children.Count() > 0)
            {
                <div class="@String.Format("{0}__Lv{1}Sub", classPrefix, lv)">
                    @renderMenu(nav.Children, classPrefix, lv + 1, String.Format("{0}-{1}", checkboxIdPrefix, nav.No))
                </div>
            }
        </div>
    }
}
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# business: http://ogp.me/ns/business#">
    <meta charset="UTF-8">
    <link rel="alternate" hreflang="en" href="https://www.aseglobal.com/@ViewBag.enURL" />
    <link rel="alternate" hreflang="zh-tw" href="https://www.aseglobal.com/@ViewBag.zhURL" />
    <!-- og -->
    <meta name="description" content="@ViewBag.Description" />
    <link rel="icon" type="image/png" href="https://3711cdn.r.worldssl.net/pic/content/ch/images/favicon_ico.png" sizes="96x96">
    <meta property="og:type" content="website">
    <meta property="og:url" content="@ViewBag.SiteUrl">
    <meta property="og:site_name" content="@ViewBag.SiteName">
    <meta property="og:title" content="@ViewBag.SiteName">
    <meta property="og:description" content="@ViewBag.SiteDesc">
    <meta property="og:image" content="@ViewBag.SiteOgImage">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>@ViewBag.HeadTitle</title>
    <link rel="shortcut icon" type="~/image/x-icon" href="favicon.ico" />
    <link rel="apple-touch-icon" href="https://3711cdn.r.worldssl.net/pic/content/ch/images/touch-icon.png" />
    <!-- Css -->

    <link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/content/ch/css/magnific-popup.css" />
    <link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/content/ch/css/all.min.css" />
    <link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/content/ch/css/ase.css?20200825-1" />
    <link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/js/vendor/sweetalert/sweetalert2.min.css" />
    <link rel="stylesheet" href="/css/ase-box.css?1" />
    <link rel="stylesheet" href="/css/ase-box-common.css" />
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/jquery/jquery-2.2.2.min.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-33905716-1"></script>

    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-33905716-1');
    </script>
    <style>
        .breadcrumbs-pc .dropdown-item:after {
            border-right: 0;
        }
    </style>
</head>

<body>
    <div id="page-loader" class="loader">
        <span>loading</span>
        <ul> <li id='a'></li> <li id='b'></li> <li id='c'></li> <li id='d'></li> <li id='e'></li> <li id='f'></li> <li id='g'></li> <li id='h'></li> <li id='i'></li> </ul>
    </div>

    <div class="ASEHeader">
        <input type="checkbox" id="MobileNavsToggle" />
        <div class="ASEHeader__Logo">
            <a class="logo pull-left holdinglogo" href="@Url.Action("Index", "Ch")">
                <img src="https://3711cdn.r.worldssl.net/pic/content/ch/images/index/asegroup_logo.png" />
            </a>
        </div>
        <div class="ASEHeader__Navs">
            @renderMenu(site_nav_list, "ASENavs")
        </div>
        <input type="checkbox" id="searchPanel" />
        <div class="ASEHeader__Search">

            <input type="checkbox" id="searchPanel" />
            <label class="btn btn-default" for="searchPanel"><i class="icon-search"></i></label>
            <div class="ASESearchPanel">
                <form action="@Url.Action("Search", "Ch")" autocomplete="off">
                    <input type="text" class="form-control" id="" placeholder="Search" name="q">
                    <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                </form>
            </div>
        </div>
        @if (ViewBag.DisabledLang == null)
        {
            <div class="ASEHeader__Lang">
                <a href="@enUrl">English</a>
                <a href="@chUrl">中文</a>
            </div>
        }

        <div class="ASEHeader__MobileToggle">
            <label class="hamburger hamburger--collapse" for="MobileNavsToggle">
                <div class="hamburger-box">
                    <div class="hamburger-inner"></div>
                </div>
            </label>
        </div>

        <div class="ASEHeader__MobileNavs">
            @renderMenu(site_nav_list, "ASEMobileNavs")
        </div>
    </div>

    <div class="page">
        <div id="wrapper">
            @RenderBody()
        </div>
    </div>

    <footer class="holdingfooter">
        <a class="gotop" href="javascript:;"><i class="icon-arrow-top"></i><span>TOP</span></a>
        <div class="col-xs-12 copyright nopadding">

      <span>
        Copyright ©
        <script type="text/javascript">myDate = new Date(); myYear = myDate.getFullYear(); document.write(myYear);</script> 日月光投資控股著作權所有
      </span>
      <span>
          <a href="@Url.Action("Contact", "Ch")">聯絡我們</a> | <a href="@Url.Action("Download", "Ch")">下載中心</a> | <a href="@Url.Action("Term_Of_Use", "Ch")">網站使用者條款</a> | <a href="/content/ch/ase_privacy.html" target="_blank">隱私權政策</a> | <a href="/content/ch/ase_cookieterm.html" target="_blank">Cookie</a> | <a href="/content/ch/sitemap.html">網站地圖</a> |
          <a style="width: 20px; height: 20px;" href="https://twitter.com/asegroup_global" target="_blank">
              <img src="https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/twitter.png" alt="Ase Group Twitter" />
          </a>
          <a style="width: 20px; height: 20px;" href="https://tw.linkedin.com/company/ase-group" target="_blank">
              <img src="https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/linkedin.png" alt="Ase Group Linkedin" />
          </a>
          <a style="width: 20px; height: 20px;" href="javascript:" data-toggle="popover" data-trigger="hover" data-placement="top" data-html="true" data-content="
          <div class='weChat'>
            <img src='https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/ASE_wechat.png' style='width:160px; height:192px' />
          </div>
        ">
          <img class="m1" src="https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/wechat.png" alt="Ase Group WeChat" />
        </a>
                <a style="width: 20px; height: 20px;" href="javascript:" data-toggle="popover" data-trigger="hover" data-placement="top" data-html="true" data-content="
          <div class='weChat'>
            <img src='https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/ase_line.png' style='width:160px; height:192px' />
          </div>
        ">
            <img class="m1" src="https://3711cdn.r.worldssl.net/pic/content/ch/images/icon/line.png" alt="Ase Group LINE" />
        </a>
            </span>
            <span>日月光投控成員：<a href="https://ase.aseglobal.com/ch" target="_blank">ASE Inc.</a> | <a href="https://www.spil.com.tw/" target="_blank">SPIL</a> | <a href="https://www.usiglobal.com" target="_blank">USI</a></span>

        </div>
    </footer>
    <div class="cookiebar">
        <div class="cookieinner">
            <p>
                為優化您的線上體驗，本網站使用Cookie。若您選擇繼續瀏覽本網站，視為您同意使用Cookie及接受本網站Cookie聲明條款。欲知悉更多Cookie的資訊，例如如何使用及停用Cookie，請參閱本網站<a href="/content/ch/ase_cookieterm.html" target="_blank">Cookie聲明</a>關於「如何變更Cookie設定或停用Cookie」的說明。
                <a href="javascript:void(0)"><div id="continuebutton" class="continuebutton">同意使用</div></a>
        </div>
    </div>
    <!-- css -->
    <link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/content/ch/css/cookie-bar.css?5" />

    <!-- JS -->

    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/jquery.mobile.custom.min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/modernizr-custom.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/jquery.matchHeight-min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/TweenMax.min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/ScrollMagic.min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/bootstrap.min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/all.js?2" async defer></script>

    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/hammer.min.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/index.js" async defer></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/csr_index.js"></script>

    <script src="https://3711cdn.r.worldssl.net/js/js/jquery.magnific-popup.js"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/magnific.js"></script>

    <script src="https://3711cdn.r.worldssl.net/js/js/cookies.js?2"></script>
    <script src="https://3711cdn.r.worldssl.net/js/js/vendor/sweetalert/sweetalert2.min.js"></script>
    <script src="~/js/ase-box-video.js?2"></script>
    @if (ViewBag.Message != null)
    {
        <script>swal({ title: "@ViewBag.Message", timer: 3000, type: "@(ViewBag.IsError != null ? "error" : "success" )" })</script>
    }
    <script>
        $(function () {
            $('.regenCode').click(function () {
                var img = $("img", this.parentElement);
                if (img.length > 0) {
                    var oldSrc = $(img).attr("src").split("?")[0]
                    $(img).attr("src", oldSrc + "?unix=" + new Date().getTime());
                }
            })
            $(".togglePassword").click(function () {
                var currentType = $("input", this.parentElement).attr('type')
                if (currentType == "password") {
                    currentType = "text"
                } else {
                    currentType = "password"
                }
                $("input", this.parentElement).attr('type', currentType);
            })
        })
    </script>
    <style>
        .togglePassword {
            position: absolute;
            right: 30px;
            top: 10px;
        }
    </style>
</body>
</html>

ASEH_Front/Views/Shared/_Layout_Content.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Base.cshtml";
}

<!-- page Banner -->
@if (!string.IsNullOrEmpty(ViewBag.BannerStyle))
{
    <section id="page-vision" class="page-banner-s @ViewBag.BannerStyle">
        <h1 class="page-title">@ViewBag.Title</h1>
    </section>
}

<!--麵包屑-->
<div class="content-lg row">
    <div class="col-xs-12">
        @Html.MvcSiteMap().SiteMapPath()
    </div>
</div>

@RenderBody()

ASEH_Front/Views/Shared/_Layout_Content_En.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Base_En.cshtml";
}

<!-- page Banner -->
@if (!string.IsNullOrEmpty(ViewBag.BannerStyle))
{
    <section id="page-vision" class="page-banner-s @ViewBag.BannerStyle">
        <h1 class="page-title">@Html.Raw(ViewBag.Title)</h1>
    </section>
}

<!--麵包屑-->
<div class="content-lg row">
    <div class="col-xs-12">
        @Html.MvcSiteMap().SiteMapPath()
    </div>
</div>

@RenderBody()

ASEH_Front/Views/Shared/_Layout_Content_En_CSR.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Base_En.cshtml";
}

<!-- page Banner -->
@if (!string.IsNullOrEmpty(ViewBag.BannerStyle))
{
    <section id="page-vision" class="page-banner-s @ViewBag.BannerStyle">
        <h1 class="page-title" style="text-align: left; padding: 20px">@Html.Raw(ViewBag.Title)</h1>
    </section>
}

<!--麵包屑-->
<div class="content-lg row">
    <div class="col-xs-12">
        @Html.MvcSiteMap().SiteMapPath()
    </div>
</div>

@RenderBody()