ASEH_Front/Models/Download/DownloadViewModel.cs
using Models;
using Service.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASEH_Front.Models.Download
{
    public class DownloadViewModel
    {
        public DownloadViewModel()
        {
            
        }

        public List<tbFile> FileList { get; set; }
    }
}

ASEH_Front/Controllers/EnController.cs
using ASEH_Backend.Services;
using ASEH_Front.Models;
using ASEH_Front.Models.Article;
using ASEH_Front.Models.Common.Quest;
using ASEH_Front.Models.Download;
using ASEH_Front.Models.ReportQuestionnaire;
using Models;
using Newtonsoft.Json;
using Service.BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using web.ViewModels.GoogleSearch;

namespace ASEH_Front.Controllers
{
    //[RequireHttps]
    [OutputCache(NoStore = true, Duration = 0)]
    public class EnController : BaseController
    {

        UserService userService = new UserService();

        public EnController()
        {
            this.lang = "en";
        }

        public ActionResult News_Login()
        {
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();
            try
            {
                validToken();
                return RedirectToAction("News_Profile");
            }
            catch (Exception)
            {

            }

            return View(new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }

        [HttpPost]
        public ActionResult News_Login(NewsUser data)
        {
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();
            var serv = new UserService();
            try
            {
                var user = serv.Login(data.Account, data.Password);
                var token = serv.GetToken(user, 180);
                Session["NewsUserToken"] = token;
                TempData["Message"] = "Login Success";
                return RedirectToAction("News_Profile");
            }
            catch (Exception err)
            {
                ViewBag.Message = "Login Failed";
                ViewBag.IsError = true;
            }

            return View(new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }


        public ActionResult News_Register()
        {
            this.Init();
            ViewBag.CountryList = Db.Country.ToList();

            return View("News_Login", new NewsUser()
            {
                Country = ViewBag.CountryList[0].Title
            });
        }

        [HttpPost]
        public ActionResult News_Register(NewsUser data)
        {

            this.Init();
            ViewBag.CountryList = Db.Country.ToList();

            var ConfirmPassword = HttpContext.Request.Form.Get("ConfirmPassword");
            var serv = new UserService();
            try
            {
                if (Request.Cookies["CAPTCHA"].Value != this.Request.Form.Get("VerifyCode"))
                {
                    throw new Exception("Sorry, Verification code error");
                }
                if (ConfirmPassword != data.Password)
                {
                    throw new Exception("Sorry, new and confirmed passwords are inconsistent.");
                }
                data.Email = data.Account;
                try
                {
                    serv.Add(data);
                } catch ( Exception )
                {
                    throw new Exception("Sorry, Email Is Duplicate");
                }
                TempData["Message"] = "Register Success";
                return RedirectToAction("News_Login");
            }
            catch (Exception err)
            {
                ViewBag.IsError = true;
                ViewBag.Message = err.Message;
            }

            return View("News_Login", data);
        }

        public ActionResult News_Logout()
        {
            this.Init();
            this.Logout();

            return RedirectToAction("News_Login");
        }

        public ActionResult News_Edit_Profile()
        {
            this.Init();
            try
            {
                var sessionData = validToken();
                var dbData = userService.GetById(sessionData.Id);

                ViewBag.CountryList = Db.Country.ToList();
                return View(dbData);
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }

        }



        [HttpPost]
        public ActionResult News_Edit_Profile(NewsUser data)
        {
            this.Init();


            try
            {
                var sessionUser = validToken();
                try
                {
                    var serv = new UserService();
                    serv.Update(sessionUser.Id, data);
                    TempData["Message"] = "Change Profile Success";
                    return RedirectToAction("News_Profile");
                }
                catch (Exception err)
                {
                    ViewBag.CountryList = Db.Country.ToList();
                    ViewBag.Message = "Sorry, Email Is Duplicate";
                    ViewBag.IsError = true;
                    return View(sessionUser);
                }
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }

        }

        public ActionResult News_Edit_Password()
        {
            this.Init();
            return View();
        }

        [HttpPost]
        public ActionResult News_Edit_Password(FormCollection form)
        {
            string Password = form.Get("Password");
            string ConfirmPassword = form.Get("ConfirmPassword");
            try
            {
                var serv = new UserService();
                var sessionUser = validToken();

                if (Password != ConfirmPassword)
                {
                    ViewBag.Message = "Sorry, new and confirmed passwords are inconsistent.";
                    ViewBag.IsError = true;
                }
                else
                {
                    userService.ResetPassword(sessionUser.Id, Password);
                    TempData["Message"] = "Change Password Success";
                    return RedirectToAction("News_Profile");
                }
                this.Init();
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }

        }

        public ActionResult News_Forget(string token)
        {
            this.Init();
            if (token != null)
            {
                try
                {
                    var dbData = userService.ValidToken(token);
                    ViewBag.Token = token;
                }
                catch (Exception err)
                {
                    ViewBag.Message = "Change Password Expired";
                    ViewBag.IsError = true;
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult News_Forget(FormCollection form)
        {
            var Token = form.Get("Token");
            if (Token == null)
            {
                // CheckEmail
                var Email = form.Get("Email");
                try
                {
                    var dbData = userService.GetByEmail(Email);

                    //return RedirectToAction("News_Forget", new
                    //{
                    //    token = userService.GetToken(dbData, 30)
                    //});
                    userService.SendForgetEmail(dbData.Id);
                    TempData["Message"] = "Email Verify Success, Please Check Email";
                    return RedirectToAction("News_Login");
                }
                catch (Exception err)
                {
                    ViewBag.Message = "The Email Not Register";
                    ViewBag.IsError = true;
                }

            }
            else
            {
                //Update Password
                var Password = form.Get("Password");
                var ConfirmPassword = form.Get("ConfirmPassword");
                if (Password != ConfirmPassword)
                {
                    ViewBag.Message = "Sorry, new and confirmed passwords are inconsistent.";
                    ViewBag.IsError = true;
                }
                else
                {
                    try
                    {
                        var tokenData = userService.ValidToken(Token);
                        userService.ResetPassword(tokenData.Id, Password);
                        TempData["Message"] = "Change Password Success, Please Use New Password Login";
                        return RedirectToAction("News_Login");
                    }
                    catch (Exception)
                    {
                        ViewBag.Message = "Change Password Expired";
                        ViewBag.IsError = true;
                        return RedirectToAction("News_Forget");
                    }
                }

            }

            this.Init();
            return View();
        }


        
        public ActionResult News_Profile()
        {
            this.Init();
            try
            {
                validToken();
            }
            catch (Exception)
            {
                return RedirectToAction("News_Login");
            }

            return View();
        }

        public ActionResult Milestones()
        {
            this.Init();
            return this.View();
        }

        public ActionResult Search(string q = "", int page = 1)
        {
            this.Init();
            string searchUrl = String.Format("https://www.googleapis.com/customsearch/v1?key=AIzaSyCoIG9dTAyeNTxVWaAPZ2leVdt8f3MZm0c&cx=017526043270526596107:s1vtx3mblil&q={0}&start={1}", q, ((page - 1) * 10) + 1);
            WebRequest req = HttpWebRequest.Create(searchUrl);

            req.ContentType = "application/json";


            GoogleSearchResult result;
            string body;
            // 取得回應資料

ASEH_Front/Views/En/CsrReport.cshtml
@model ASEH_Front.Models.Download.DownloadViewModel

@{
    ViewBag.Title = "CORPORATE SOCIAL RESPONSIBILITY";
    ViewBag.BannerStyle = "banner-csr";
    Layout = "~/Views/Shared/_Layout_Content_En_CSR.cshtml";
}

<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">CSR Report Downloads</h3>
        </article>
        @foreach (var item in Model.FileList)
        {
            <div class="col-sm-6 col-md-4 padding-bottom40 text-center">
                <a href="@Url.Action("CsrReportDownload", new { id = item.FieID })" class="link-block download_btn" data-id="29" target="_blank">
                    <img src="@Url.Content(string.Format("~/uploads/{0}/{1}", item.FieID, item.FiePicPath_EN))">
                    <p class="reports">
                        <br>
                        @item.FieName_EN<br>
                    </p>
                    <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                </a>
            </div>
        }
        <div class="panel-group col-xs-12" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="col-md-12 bgnews-list list-base panel">
                <div class="content">
                    <a href="http://csr.usish.com/e_download.php" target="_blank">
                        <span class="blue-text-in-box accordion-center-text">USI CSR Report</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

ASEH_Front/Views/En/Csr_Download.cshtml
@model ASEH_Front.Models.Download.DownloadViewModel

@{
    ViewBag.Title = "Committed to<br />a Win-Win Sustainable Future";
    ViewBag.BannerStyle = "banner-csr";
    Layout = "~/Views/Shared/_Layout_Content_En_CSR.cshtml";
    ViewBag.HeadTitle = "CSR Report Downloads | ASE Technology Holding";
    ViewBag.Description = "Get ASE Technology Holding Corporate Sustainability Report (CSR) Report";
    ViewBag.enURL = "en/csr_download";
    ViewBag.zhURL = "ch/csr_download";
}

<section class="inside-article">
    <div class="content-lg row">
        <div class="col-xs-12">
            <h3 class="title">CSR Report & Video Downloads</h3>
        </div>
    </div>
</section>
<br>
<section class="csr-bg">
    <div class="content-lg row">
        <div class="col-sm-4 col-sm-offset-4 csr">
            <div class="col-md-12 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Report", "En")">
                        <span class="blue-text-in-box">CSR Report Downloads</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            @*<div class="col-md-6 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Video", "En")">
                        <span class="blue-text-in-box">CSR Video Downloads</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>*@
            <div class="clearfix"></div>
        </div>
    </div>
</section>

ASEH_Front/Views/En/Csr_Report_Questionnaire.cshtml
@model ASEH_Front.Models.ReportQuestionnaire.ReportQuestionnaireViewModel2
@{
    ViewBag.Title = "CORPORATE SOCIAL RESPONSIBILITY";
    ViewBag.BannerStyle = "banner-csr";
    Layout = "~/Views/Shared/_Layout_Content_En_CSR.cshtml";

    var options = Model.getOptions();
    var Lang = Model.Lang;
}
<style>
    .rq-table th, .rq-table td {
        font-size: 16px !important;
    }

    .rq-table thead td {
        font-weight: bold;
    }
</style>
<section class="inside-article" style="font-size:16px!important;line-height: 28px;">
    <div class="content-lg row">
        <article class="col-xs-12">
            @using (Html.BeginForm("Csr_Report_Questionnaire", "En", FormMethod.Post, new { @class = "form-inline" }))
            {
                @Html.AntiForgeryToken()

                <h3 class="title">@(Model.getTitle().getText(Lang))</h3>
                <p style="font-size: 1.1rem;">
                    @(Model.getSummer().getText(Lang))
                </p>

                foreach (var section in Model.getSections())
                {
                    <h4 class="sub-title">@(section.getText(Lang))</h4>
                    if (section.StackholderList != null)
                    {
                        <div>
                            @foreach (var stackholder in section.StackholderList)
                            {
                                <div class="col-sm-4">
                                    <label class="radio-inline">
                                        <input type="radio"
                                               name="stakeholder"
                                               value="@(stackholder.Key)"
                                               @(Model.stakeholder == stackholder.Key ? "checked" : "")> @stackholder.getText(Lang)
                                            @if (section.StackholderList.IndexOf(stackholder) == (section.StackholderList.Count - 1))
                                            {
                                                <input type="text" class="form-control" name="other" style="height:24px;" value="@(Model.other)">
                                            }
                                        </label>
                                    </div>
                                }
                            <div class="col-sm-12">
                                <div class="form-group">
                                    @if (@ViewData["stakeholder"] != null)
                                    {
                                        <span style="color: red;">@ViewData["stakeholder"]</span>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                    else if (section.TopicList != null)
                    {
                        <div class="table-responsive inside-table rq-table">

                            <div class="quest_form">
                                <div class="quest_form__header">
                                    <div class="quest_form__body">
                                        <div>
                                            <strong class="txt_bold">
                                                @Model.getTableHeader1().getText(Lang)
                                            </strong>
                                            (@Model.getTableHeader2().getText(Lang))
                                        </div>
                                    </div>
                                    <div class="quest_form__options">
                                      <div class="quest_form__options__title">
                                        @Model.getTableHeader3().getText(Lang)
                                      </div>
                                      @foreach (var option in options)
                                      {
                                        <div>@option.getText(Lang)</div>

                                      }
                                    </div>
                                </div>
                                <div class="quest_form__group">
                                    @foreach (var topic in section.TopicList)
                                    {
                                        <div class="quest_form__topic">
                                            <div class="quest_form__body">
                                                <div class="form__body__col">
                                                    <h4>
                                                        <strong>@topic.Issue.getText(Lang)</strong>
                                                    </h4>
                                                    <div>
                                                        @topic.Content.getText(Lang)
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="quest_form__options">
                                                @foreach (var option in options)
                                                {
                                                <label>
                                                    <input type="radio" name="@topic.Key" value="@option.Key">
                                                    <span class="quest_form__optionText">@option.getText(Lang)</span>
                                                </label>
                                                }
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                    else if (section.isYesOrNo)
                    {
                        <label>
                            <input type="radio" name="@(section.Key)" value="YES"> YES
                        </label>
                        <label>
                            <input type="radio" name="@(section.Key)" value="NO"> NO
                        </label>
                    }
                    <p>&nbsp;</p>
                }
                <div class="col-sm-12">
                    <h4 class="sub-title">*@Model.getLast().getText(Lang)：</h4>
                    <textarea class="form-control" name="additional" rows="5" style="min-width: 100%">@(Model.additional)</textarea>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <br>
                        <br>
                        <h4 class="sub-title inline">*@Model.getValid().getText(Lang):</h4>
                        <input type="text" name="vcode" class="form-control" required style="border-color: #CCCCCC" />
                        <img id="captcha" src="~/CAPTCHA.ashx" style=" position:relative; width:100px; height:40px;" />
                        <button onclick="regenVcode()" type="button">Re Generate Verification</button>
                        @if (@ViewData["captcha"] != null)
                        {
                            <span style="color: red;">@ViewData["captcha"]</span>
                        }
                    </div>
                </div>
                <div class="col-xs-12 section-contact">
                    <div class="content-wrapper pull-left">
                        <button type="reset" style="margin-left:30px">@Model.getCancelButton().getText(Lang)</button>
                        <button type="submit">@Model.getSubmitButton().getText(Lang)</button>
                    </div>
                </div>
                <input type="hidden" name="fieid" value="@Model.FieId">
            }
        </article>
    </div>
</section>
<link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/js/vendor/sweetalert/sweetalert2.min.css" />
<link rel="stylesheet" href="https://3711cdn.r.worldssl.net/css/css/quest.css" />
<script src="https://3711cdn.r.worldssl.net/js/js/vendor/sweetalert/sweetalert2.min.js"></script>

@if (@ViewData["msg"] != null)
{
    <script>swal({ title: '@ViewData["msg"]', timer: 3000, type: 'success' })</script>
}

<script>

    function regenVcode() {
        var img = document.querySelector("#captcha");
        var newSrc = img.getAttribute('src').split('?')[0];
        newSrc = newSrc + '?unix=' + new Date().getTime();
        img.setAttribute("src", newSrc)
    }
</script>

ASEH_Front/Views/En/Csr_Sustainability_Governance.cshtml
@{
    ViewBag.Title = "Committed to<br />a Win-Win Sustainable Future";
    ViewBag.BannerStyle = "banner-csr";
    Layout = "~/Views/Shared/_Layout_Content_En_CSR.cshtml";
    ViewBag.HeadTitle = "Sustainability Governance | ASE Technology Holding";
    ViewBag.Description = "We drive sustainability through proper management of opportunities and risks, aligning business models with stakeholders, and adjust the direction and goals of sustainable development accordingly.";
    ViewBag.enURL = "en/csr_sustainability_governance";
    ViewBag.zhURL = "ch/csr_sustainability_governance";
}

<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">Sustainability Governance</h3>
            <p>
                We drive sustainability through proper management of opportunities and risks, aligning business models with stakeholders, and adjust the direction and goals of sustainable development accordingly.
            </p>
        </article>
    </div>
</section>
<!--Button-->
<section class="csr-bg">
    <div class="content-lg row">
        <div class="col-xs-12 csr">
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Corporate_Sustainability_Policy", "En")">
                        <span class="blue-text-in-box">Corporate Sustainability Policy</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Sustainability_Strategy", "En")">
                        <span class="blue-text-in-box">Sustainability Strategy</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="~/content/en/csr_organization_structure.html">
                        <span class="blue-text-in-box">Organization and Structure</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xs-12 csr">
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Business_Conduct_Ethics", "En")">
                        <span class="blue-text-in-box">Business Conduct and Ethics</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("Csr_Human_Rights_Management", "En")">
                        <span class="blue-text-in-box">Human Rights Management</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="~/content/en/csr_regulatory_compliance.html">
                        <span class="blue-text-in-box">Regulatory Compliance</span>
                        <div class="circle_button-wrapper">
                            <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xs-12 csr">
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="~/content/en/csr_risk_management.html">
                        <span class="blue-text-in-box">Risk Management</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="https://ir.aseglobal.com/html/ir_corpor.php">
                        <span class="blue-text-in-box">Board of Directors</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="~/content/en/csr_succession_planning.html">
                        <span class="blue-text-in-box">Succession Planning</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xs-12 csr">
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="~/content/en/csr_information_security_management_policy.html">
                        <span class="blue-text-in-box">Information Security Management</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 bgnews-list list-base">
                <div class="content">
                    <a href="@Url.Action("IP_Management", "En")">
                        <span class="blue-text-in-box">Intellectual Property Management</span>
                        <div class="circle_button-wrapper pull-right">
                            <div class="circle_button darkgray pull-right"><i class="icon-arrow-right"></i></div> 
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

ASEH_Front/Views/En/PressRoom.cshtml
@model ASEH_Front.Models.Article.ArticleViewModel

@{
    ViewBag.Title = "Press Room";
    ViewBag.BannerStyle = "banner-press_room";
    Layout = "~/Views/Shared/_Layout_Content_En.cshtml";
}

<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">Press Room</h3>
        </article>
    </div>
</section>
<section class="page-list-content">
    <div class="content-lg row">
        <ul class="col-xs-12 list-base list-link list-timetip-line">
            @foreach (var item in Model.ArticleList)
            {
                <li>
                    <a href="@Url.Action("PressRoomDetail", new { Id = item.AtcID })">
                        <div class="date">@item.AtcOpenDate.Value.ToString("yyyy/MM/dd")</div>
                        <div class="text-box">
                            <h4 class="title">@item.AtcName_EN</h4>
                            <div class="circle_button-wrapper">
                                <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                            </div>
                        </div>
                    </a>
                </li>
            }
        </ul>
    </div>
</section>